# Generated by Django 5.2.8 on 2025-11-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="mdi-help-circle", max_length=50),
        ),
    ]
